### ISSUE TITLE
Weird controller tracking

### ISSUE THREAD

**Issue by OFlexan** [Timocop/PSMoveServiceEx-Virtual-Device-Manager#16]
I have set up the PS move controllers using the debug config tool and calibrated them using the A4 pose method. I can actually play VR games now, however, even though the config tool shows that the colors are tracked correctly, and the test pose window showing that the positions are good (except for the rotation, more on that later), the controllers often glitch in games. Although that isn't my main concern.

My main concern is that the controllers seem to be really hard to setup correctly. One issue that is persistent is that the tool thinks that when the controller is standing up, it points forward. So when I point the controller forward, it points downwards in game (seems like roll is 90 degrees offset). I have no idea how to change it.

Another random thing that only happened just now (after several retries of calibrating and re-setting up) is that when I move the controllers up, they move down. The controllers are also really close to my body and one of them is inverted (although I can fix that by holding the options button). Is there a reliable way to fix all of these issues?

![image](https://github.com/Timocop/PSMoveServiceEx-Virtual-Device-Manager/assets/93340481/a52abf68-532f-478b-a218-cb5e14111a0f)

**Comment by Timocop** [comment]
Can you please list your whole setup, devices, logs and screenshots of all related settings. That screenshot is a big nothing-burger.

**Comment by OFlexan** [comment]
The order that this comment is written in is the order of how I setup the settings each time.

I'm using my phone for a camera using DroidCam (virtual tracker):
![image](https://github.com/Timocop/PSMoveServiceEx-Virtual-Device-Manager/assets/93340481/a7452c22-04ad-4f20-b59b-f0ec41125d1d)
(setting distortion preset doesn't let the error go away, so not sure what that's about)

I'm using a desktop computer with Windows 10 with the graphics card being an AMD Radeon R7 200 series.

The devices are:
- PSVR headset
- two PS move controllers
- virtual tracker/camera from earlier
![image](https://github.com/Timocop/PSMoveServiceEx-Virtual-Device-Manager/assets/93340481/995ae77c-0d6b-42fb-8180-f3bae832fd2d)

In the debug config tool, in `Tracker Settings -> Calibrate Tracking Colors` it both shows that there are no issues (I play about 2-2.5 meters from the camera which is enough space and doesn't show collisions, I track only the controllers):
![image](https://github.com/Timocop/PSMoveServiceEx-Virtual-Device-Manager/assets/93340481/d3308825-e60f-4a31-a719-3405a4cb0cd3)

After grabbing a board and putting on the A4 pose calibrating paper, I follow the instructions and repeat for both controllers. When calibrated, the first issue arises. Whenever I move the controller up, it moves down, and vice-versa. For the rest it seems to be tracking pretty well and smooth:

https://github.com/Timocop/PSMoveServiceEx-Virtual-Device-Manager/assets/93340481/b3a7c696-c039-4c1d-94ef-1c42a2211885

At the time of testing this, the controllers seem to both be rotated correctly now (which wasn't the case in the original question), so not sure what that was about either or how it got fixed, but that works now.

Next I add OSC devices:
![image](https://github.com/Timocop/PSMoveServiceEx-Virtual-Device-Manager/assets/93340481/0fb0c463-926a-4f47-81a3-39671ddcb06a)
and launch SteamVR and the OSC server.

The headset is calibrated to 180 cm in SteamVR.

Because of the controllers seeming to be accurately and smoothly tracked in the config tool, I expected that it would work perfectly in practice. However, the controllers seem to be glitched out often in both SteamVR environment and games like VRChat (and again, the Y axis is inverted):

https://github.com/Timocop/PSMoveServiceEx-Virtual-Device-Manager/assets/93340481/7cf0f401-75e5-4345-82bc-7e8030491411

Logs:
[PSMoveServiceEx.log](https://github.com/user-attachments/files/16088944/PSMoveServiceEx.log)
[application_error.ini](https://github.com/user-attachments/files/16088958/application_error.ini.txt)

PlayStation VR drivers are installed and the headset display is in virtual mode.

**Comment by Timocop** [comment]
There are several issues with this setup.

- **One camera**
Avoid using one camera tracking. As one camera tracking uses the LED bulb size to measure depth which is terribly unprecise especially when using custom tracking bulbs. If you have no other choice dont use 480p, use 1080p instead. But keep in mind, tracking quality is heavly limited.

 - **Improper webcam settings**
Why did you **unflip** the webcam image (**VDM > Virtual Trackers > Flip image horizontally**) ?. Please see **HELP** (on the same page as the settings) for more information. This is why your tracking is inverted. 
Also IP Webcams are unsupported and cause a lot of trouble. Such as increased latency, terrible image compression and weird distortion. Cameras should be permanently mounted to have the best performance and tracking quality.
Not only that but also one camera tracking isnt recommended either (see above). 

- **Uncalibrated distortion values**
Due to different cameras having a fish eye effect, this effect can cause tracking abnormalities because the image is distorted and needs to be straighten in order to track things correctly in 3d space. Most of the time on 1 or 2 cameras this isnt necessary but if you have 3 or more cameras, the distortions becomes more pronoun causing tracking offsets.
You have to print the lens calibration chessboard pattern in the ``assets`` folder of PSMoveServiceEx and calibrate the lens by holding it in front of it.

- **Uncalibrated color for devices**
The logs say you didnt calibrate the colors of any of your devices. Controllers are not calibrated nor your HMD is. Open up color calibration and setups all colors correctly.

- **Pose calibration**
If you just use one camera, pose calibration is not required. Unless your camera is angled in a different way (not looking straight forward). Pose calibration is only required so sync multiple cameras together to enable triangulation between the cameras to give me precise tracking.

Please show every tab in **VDM > Virtual Motion Tracker** such as settings and overrides etc.

**Comment by Timocop** [comment]
I assume this issue has been resolved due to no response. If this problem still occurs, reopen this issue.

**Comment by OFlexan** [comment]
It's not resolved. I wasn't home and Github's stupid 2FA makes it so I can only login on my home computer. I'll revisit this some later time.

**Comment by Timocop** [comment]
You can always join the PSMoveServiceEx Discord (no account required). Im more active there and more community members can help with you out as well.

Did you follow the steps above?
